export const SKILLS_LIST = [
  'React',
  'Next.js 13',
  'TypeScript',
  'JavaScript',
  'Redux toolkit',
  'i18next',
  'REST Api / GraphQL',
  'Webpack / ESLint',
  'Vite',
  'Jest',
  'Git / GitHub',
  'HTML',
  'CSS / Sass',
  'Figma',
];
